name: Update Popular Movie JSON

on:
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা পর পর অটোমেটিক আপডেট হবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python script.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add "Popular movie.json"
          git commit -m "Auto-update Popular movie.json via workflow [skip ci]" || exit 0
          git push
          
